### ISSUE TITLE
unpack_hilo()

### ISSUE THREAD

**Issue by RTHuber** [mitchelloharawild/moment#5]
Hi Mitchell,

It seems that unpack_hilo() no longer works since I installed last week's updates. When I run the familiar code:

library(tidyverse)
library(fable)
result <- as_tsibble(USAccDeaths) %>%
  model(arima = ARIMA(log(value) ~ pdq(0,1,1) + PDQ(0,1,1)))%>%
  forecast(h=12)

result %>% 
  hilo(level = c(80, 95)) %>% 
  unpack_hilo("80%")

I keep getting the following error message:

Error in `tidyr::unpack()`:
! Can't rename variables in this context.

Do you know what to do to get unpack_hilo() working again?

Many thanks for your help!
Reto

**Comment by mitchelloharawild** [comment]
Fixed in development version of fabletools here: https://github.com/tidyverts/fabletools/commit/dd9027da9c21d99b9f2c8dbb662d7ae465933e68
I think this was introduced as a bug in tidyr v1.3.0
